### ISSUE TITLE
Email password exposure

### ISSUE THREAD

**Issue by tonyyang132** [kparal/sendKindle#2]
To send a document out, I need to configure Email password either in the configuration file or as a parameter in command line. Both manners will expose the password in plain text. I would like a third option if the first two are not available, that the password be obtained from terminal with no echo.

**Comment by jiangmitiao** [comment]
I‘m writing something like yours sendKindle,but I find an question.I can send mail to any mailbox which is not Kindle's .But I can't success to send mail to Kindle's box .What should I do?is this smtplib's problem？

**Comment by kparal** [comment]
This got fixed in #3
